apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: namespace1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: maxjokar2020/fastapi-app1:latest
          ports:
            - containerPort: 5000